Navbar='<div id="navbar"><ul>
	<li id="nibbles"><a href="index.html">Nibbles</a></li>
	<li><a href="tutorial_basics.html">Tutorial: Basics</a> | <a href="tutorial_ancillary.html">Ancillary</a> | <a href="tutorial_minutiae.html">Minutiae</a></li>
	<li><a href="quickref.html">Quick Ref</a></li>
	<li><a href="https://github.com/darrenks/nibbles">Code: Github</a> | <a href="nibbles-latest.tgz">Download</a></li>
</ul></div>'


'
<div id="navbar"><ul>
	<li><a href="index.html">Home</a></li>
	<li>Tutorial
		<ul>
			<li><a href="tutorial_basics.html">Basics</a></li>
			<li>Intermediate</li>
			<li>Advanced</li>
		</ul>
	</li>
	<li><a href="quickref.html">Quick Ref</a></li>
	<li>Code
	<ul>
		<li><a href="https://github.com/darrenks/nibbles">github</a></li>
		<li><a href="nibbles-latest.tgz">download</a></li>
	</ul>
	</li>
</ul></div>
'

allFiles = `cd docs; echo *.md`.split

def convertMd(filename)
	basefile = filename.sub(/\.md$/,'')
	markdown = `markdown.pl docs/#{filename}`
	title = markdown[/<h1>(.*?)<\/h1>/,1]
	if title.nil?
		puts 'skipping '+filename
		return
	end
	File.open('web/site/'+basefile+'.html','w'){|f|f<<'<!DOCTYPE HTML>
<html><!-- This file is automatically generated from generate_site.rb by reading '+filename+' --><head><title>'+title+'</title><link rel="stylesheet" href="style.css"></head><body>'+Navbar+'<div id="content">'+markdown.gsub(
	'QuickRef','<a href="quickref.html">Quick Ref</a>').gsub(
	'$Feedback','Bug reports, suggestions, and code reviews are appreciated (I\'m new to Haskell), make a push request or email me at <img src="email.png" alt="Image of email" title="" />.') # todo replace in md and also do for "details"
+'</div></body></html>'}
end

allFiles.each{|f|
	convertMd(f)
}